##ES 654 Prerequisite Test

Q1

Number of Multiplications = $k \times m \times n$  
Number of additions = $(k-1) \times m \times n$

The resulting matrix will contain $m \times n$ entries when matrices of size $(n, k)$ and $(k, m)$ are multiplied together. Each of these entries will contain k product terms (k columns of first matrix and k rows of second matrix) added together by (k-1) additions.

Q2

In [8]:
import numpy as np
import time

In [34]:
# Let n = 4, k = 2, m = 3

# (4, 2)
x = [[4, 3], 
     [5, 8], 
     [1, 2], 
     [9, 10]]

# (2, 3)
y = [[4, 1, 9], 
     [7, 3, 5]]

# (4, 3) -- Resultant Matrix
z = [[0, 0, 0], 
     [0, 0, 0], 
     [0, 0, 0], 
     [0, 0, 0]]

In [37]:
print("Matrix Multiplication by List of Lists")

start = time.time()
for i in range(len(x)):
  for j in range(len(y[0])):
    for k in range(len(y)):
      z[i][j] += x[i][k] * y[k][j]

print(time.time() - start)
print(z)

Matrix Multiplication by List of Lists
0.0002071857452392578
[[74, 26, 102], [152, 58, 170], [36, 14, 38], [212, 78, 262]]


In [38]:
print("Matrix Multiplication by numpy")
start_ = time.time()
z_ = np.matmul(x, y)
print(time.time() - start_)
print(z_)

Matrix Multiplication by numpy
0.00019311904907226562
[[ 37  13  51]
 [ 76  29  85]
 [ 18   7  19]
 [106  39 131]]


It can be observed that matrix multiplication is very slightly faster when done using numpy. However, if we repeat the time measurements we also find instances when the numpy method is slower. Both the above methods follow the trivial matrix multiplication performed in $O(n^3)$ and thus do not differ much in execution time.

Numpy relies on optimzied BLAS libraries, whenever possible, to provide efficient low level implementations of the matmul function. However, these libaries depend of the processor and need to be controlled explicitly. 

Q4

Gradient w.r.t. x ==> $2xy + y^3cos(x)$

Gradient w.r.t. y ==> $x^2 + 3y^2sin(x)$

Q6

In [43]:
from sympy import diff, sin
from sympy.abc import x,y

expr = (x**2)*y + (y**3)*sin(x)

gradient_x = diff(expr, x)
gradient_y = diff(expr, y)

print(gradient_x)
print(gradient_y)

2*x*y + y**3*cos(x)
x**2 + 3*y**2*sin(x)


We can see that the gradients obtained using sympy are same to the ones obtained analytically. 

Q7

In [44]:
Student_Information = {
    2022: {
        "Branch 1": {
            "Roll Number": 1, 
            "Name": "A", 
            "Marks": {
                "Maths": 100, 
                "English":100
                }
        },
        "Branch 2": {
            "Roll Number": 2, 
            "Name": "B", 
            "Marks": {
                "Maths": 99, 
                "English":99
                }
        }
    },
    2023: {
        "Branch 1": {
            "Roll Number": 1, 
            "Name": "C", 
            "Marks": {
                "Maths": 98, 
                "English":98
                }
        },
        "Branch 2": {
            "Roll Number": 2, 
            "Name": "D", 
            "Marks": {
                "Maths": 97, 
                "English":97
                }
        }
    },
    2024: {
        "Branch 1": {
            "Roll Number": 1, 
            "Name": "E", 
            "Marks": {
                "Maths": 96, 
                "English":96
                }
        },
        "Branch 2": {
            "Roll Number": 2, 
            "Name": "F", 
            "Marks": {
                "Maths": 95, 
                "English":95
                }
        }
    },
    2025: {
        "Branch 1": {
            "Roll Number": 1, 
            "Name": "G", 
            "Marks": {
                "Maths": 94, 
                "English":94
                }
        },
        "Branch 2": {
            "Roll Number": 2, 
            "Name": "H", 
            "Marks": {
                "Maths": 93, 
                "English":93
                }
        }
    }
}

Q13

In [56]:
import numpy as np

def argmin(x):
  min = x[0]
  index = 0
  for i in range(len(x)):
    if min > x[i]:
      min = x[i]
      index = i
  return index


arr = np.random.rand(10, 1)
print(arr)
print()
print(argmin(arr))

[[0.42678249]
 [0.36598378]
 [0.35833729]
 [0.63748157]
 [0.92017974]
 [0.39561507]
 [0.83040158]
 [0.37211866]
 [0.40407068]
 [0.96072742]]

2


In [57]:
print(np.argmin(arr))

2


We can see that np.argmin gives the same output as the defined argmin function.